apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nodejs 
  namespace: argocd 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: dev-nodejs
spec:
  destination:
    namespace: application-dev 
    server: 'https://kubernetes.default.svc'
  source:
    path: config/dev-nodejs
    repoURL: 'https://github.com/cdxooopz/argocd-workflow.git' 
    targetRevision: HEAD 
    directory:
      recurse: true 
  project: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOption:
    - CreateNamespace=true